### ISSUE TITLE
Error running interactive shell: 'module' object has no attribute '_start_backend'

### ISSUE THREAD

**Issue by ViktorNova** [dsacre/mididings#15]
I just stumbled on your GitHub repo, very cool to see mididings is continuing to evolve!

I'm trying to run the interactive shell with ````mididings -J -s```` and am getting this error:

````
Traceback (most recent call last):
  File "/usr/bin/mididings", line 282, in <module>
    app.run_interactive(args[0] if len(args) else None, False)
  File "/usr/bin/mididings", line 152, in run_interactive
    mididings.engine._start_backend()
AttributeError: 'module' object has no attribute '_start_backend'
````
same error when I use -A or -R too, and I can run it in print mode just fine 
(haven't tested anything else yet) I didn't notice any errors while compiling, so I'm assuming it is installed correctly?

**Comment by dsacre** [comment]
It sounds a lot like you have more than one version of mididings installed. The `mididings` command line tool is a recent version (otherwise it would complain about the `-s` argument), but the `mididings` python module it loads appears to be an older version (the missing function it complains about was added around the same time as the interactive shell feature).

Please try to remove any previous installation of mididings. Running `python -c "import mididings; print mididings"` should point you to the module that actually gets loaded.

It might also be helpful for me to know whether the previous version came from a distro package or a manual install.

**Comment by ViktorNova** [comment]
Aha, that was it, I did have mididings previously installed through apt, which I had removed, but I didn't realize python-mididings was a separate package and it was still installed. Thanks!
